### ISSUE TITLE
Version management / update strategy

### ISSUE THREAD

**Issue by chrismayer** [terrestris/BasiGX#98]
I wondered if there is (or if there are plans) for a version management of BasiGX. Since the version number is `1.0.0` from the beginning the automatic upgrade of this package with Sencha CMD seems to be difficult.

Are there any stategies how this is handled at the moment by other devs?
Are there plans to introduce a sustainable version management?

**Comment by weskamm** [comment]
Hi Christian,

Correct, currently there is no sencha like version management. Most projects are using the latest master as a git submodule, so commits need to be tested by the different developers of that applications to see if it behaves nicely.
You can still use BasiGX at a fixed commit as a submodule, just as simple as a checkout of that commit and commit in the father repository of the submodule.

Things may very well change in the near future, where BasiGX will get more attention and rework, due to a bigger project. I think the developers will inform here if the current strategy changes

**Comment by chrismayer** [comment]
Hi @weskamm !

Thanks for your detailed explanations. The strategy with the git submodules is a very practical one. Will do the trick in a pure git based environment.

I also played a bit around with ``sencha repo sync``, but this did not do it (at least for me). If someone else got this working he can post the solution here.

**Comment by weskamm** [comment]
I just created an npm package for basigx on the current state and tagged it as v1.0.0
https://www.npmjs.com/package/@terrestris/basigx
Also, the sencha packaging mechanism has been removed, as it wont be supported any longer.
Closing this issue now.
